### ISSUE TITLE
Set multiple attributes with one URL call

### ISSUE THREAD

**Issue by fredlcore** [staromeste/homebridge-http-advanced-accessory#28]
First of all, thanks a lot for this great plugin!
I have the problem that for my "thermostat" device, I could get all the relevant data in one URL call. Is it possible to assign multiple thermostat-variables with just one URL call, e.g. "getTemperatureDisplayUnits" and "getCurrentTemperature"?
Because now I have to send five URLs and my device can't handle that many at the same time and some get returned with error "ECONNREFUSED" and are thus undefined.

The other alternative would be to add a short delay between URL calls. Is there a setting for that?

**Comment by staromeste** [comment]
I'm sorry but unfortunately there is no setting for this. But it wouldn't
be so difficult to add... I'll schedule it as soon as possible.

**Comment by fredlcore** [comment]
Thanks a lot for your quick response and your offer to look into it!

**Comment by staromeste** [comment]
I've added a configuration option "uriCallsDelay" to add a delay between
calls. Let me know if it works for you.

**Comment by fredlcore** [comment]
Great, works like charm, thanks a lot for this quick fix!
