### ISSUE TITLE
Unable to start new homebridge 1.3.0

### ISSUE THREAD

**Issue by Snooppy78** [staromeste/homebridge-http-advanced-accessory#30]
Hi, Encounter this issue with this plug in.  Homebridge unable to start.  Remove the accessory and homebridge is ok.

Error are as below.  Not sure if anyone encounter this.  Error happen after upgrade to new homebridge.

Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] [homebridge-http-advanced-accessory] This plugin generated a warning from the characteristic 'Name': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
**Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] TypeError: Cannot read property 'url' of undefined
Feb 22 14:31:31 homebridge homebridge[6305]:     at HttpAdvancedAccessory.<anonymous> (/usr/lib/node_modules/homebridge-http-advanced-accessory/index.js:218:68)
Feb 22 14:31:31 homebridge homebridge[6305]:     at HttpAdvancedAccessory.<anonymous> (/usr/lib/node_modules/homebridge-http-advanced-accessory/index.js:404:8)
Feb 22 14:31:31 homebridge homebridge[6305]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-http-advanced-accessory/node_modules/polling-to-event/index.js:77:5)
Feb 22 14:31:31 homebridge homebridge[6305]:     at ontimeout (timers.js:436:11)
Feb 22 14:31:31 homebridge homebridge[6305]:     at tryOnTimeout (timers.js:300:5)
Feb 22 14:31:31 homebridge homebridge[6305]:     at listOnTimeout (timers.js:263:5)
Feb 22 14:31:31 homebridge homebridge[6305]:     at Timer.processTimers (timers.js:223:10)**
Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] [Yeelight] 0x00000000049dacbc: failed communication attempt 0 after 100ms.
Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] [Broadlink RM] Living Room Air Conditioner onTemperature (28.3)
Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] [Broadlink RM] Bedroom Air Conditioner onTemperature (29.8)
Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] [TuyaLan] Connected to Bedroom Lamp 2
Feb 22 14:31:31 homebridge homebridge[6305]: [TuyaAccessory] Sending first query to Bedroom Lamp 2 (3.3)
Feb 22 14:31:31 homebridge homebridge[6305]: [2/22/2021, 2:31:31 PM] Got SIGTERM, shutting down Homebridge...

**Comment by staromeste** [comment]
It looks like the configuration is not complete. Can you post the
config.json?

**Comment by Snooppy78** [comment]
I manage to resolve it by adding a getName to the API as previously it's working without the method.  Thanks!

**Comment by staromeste** [comment]
Can you please post the solution?

**Comment by ravedoglv** [comment]
Staromeste, are you still working on this plugin… am stuck and opened up another ticket
